### ISSUE TITLE
My opinion

### ISSUE THREAD

**Issue by 1033Forest** [ListenerJubatus/SM-ThreePointNine#12]
This theme, it looks good so far. But I don't really like the new graphics. I'd like it to look as much as 3.9 as possible.

**Comment by Inorizushi** [comment]
This theme isn't meant to be a straight port of just 3.9

We're incorporating all flavors of the 3.9 default theme.

The reason why there's new graphics is because if the originals would ise, it'd look like crap.

**Comment by 1033Forest** [comment]
Oh... So there's 5 style buttons, there is another style for Dance mode, which is 3 panel (left/down/right in 5.0; upleft/down/upright in 5.1). 3 panel originally came from DDR Solo 2000, and the first and third tracks can be hit with the diagonals or left/right. Can a button for that be added? It is a 1 player only style

**Comment by ListenerJubatus** [comment]
No, 3-panel died after DDR Solo.
