### ISSUE TITLE
Name entry screen

### ISSUE THREAD

**Issue by 1033Forest** [ListenerJubatus/SM-ThreePointNine#13]
http://wuargh.com/kiyi/stepmaniascore.JPG

I remember seeing a screen like this in 3.9, after playing all 3 songs and seeing my results.

Can a screen like this come back in this theme? (the font and background will obviously be different as this is not CyberiaStyle)

To use this screen: Once the letter of your choice scrolls up on the receptors, hit the arrow panel where you want that letter to be in your name. For example, for the name EVNT, E left, V down, N up, and T right. Since the old 3.9 version did not support numbers and symbols, this one can.

For double, use P1's pad to enter a name. For solo, use left, upleft, down, and up. For 3 panel, IDK what button should be used for the 4th letter.

For pump or techno 5, use the corners to enter your name and the center button to confirm.

**Comment by ListenerJubatus** [comment]
I don't know if this stuff is even implemented or still works on SM5.

**Comment by 1033Forest** [comment]
We should probably ask a SM developer first...
